### ISSUE TITLE
Can go to the  editing model page that I'm not the owner (via URL)

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#23]
Just add /edit in the URL ... should be locked !

https://testplatform.aigang.network/data/fab19752ea95464bb770871bd2de83c8/models/85c18329d721496c94aaae4051b8fde8/edit

Then there is a warning message  : 
![image](https://user-images.githubusercontent.com/3889245/39513149-aadea960-4df3-11e8-9a8c-7197f2128ddc.png)

This message should be there before seeing all the fields 

Seems like the i18n translation for  'errors.validation.Forbidden' is also missing (from the console) :-)

**Comment by DomantasP** [comment]
Fixed

**Comment by dyoann** [comment]
I checked, it works well for the data (shows a page with "not found").
With the model edit also, even if  we see a quick redirect to some /forbidden page 
(but we can still see the page quickly !  )

I noticed something weird also by looking at network traffic, see below : 


It seems (by checking by hand) that the first parameter is useless in the API : 
![image](https://user-images.githubusercontent.com/3889245/39629350-2a43ceb0-4fac-11e8-8f31-0d7dd61015d4.png)

I think also that we shouldn't be able to access an API call like this one if the content is still 
in moderation (if we are not the owner, otherwise it doesn't matter)

**Comment by DomantasP** [comment]
First of all I changed "/forbidden" route to "/access-denied" to be a bit more consistent with the naming. 

If you go to ".../data/edit/dataset-id-you-are-not-the-owner-of" you should be redirected to "/access-denied" and I not sure how did you managed to get "Not found" page.

"but we can still see the page quickly" - I optimized redirecting a little, but we need to await the response from the api before knowing that access is denied for this page, that's why an empty form will be shown quickly before redirecting.

**Comment by DomantasP** [comment]
I fixed the problem with undefined dataset id. Now it's being validated on the back-end and it always must be sent to the api.
